### ISSUE TITLE
A gradle build failure should fail the whole build

### ISSUE THREAD

**Issue by mboes** [tweag/sparkle#64] opened 2016-11-24 09:43 UTC
As initially reported by @robinbb in https://github.com/LeapYear/sparkle/issues/2#issuecomment-262410120, the return code of Gradle seems to be ignored.

Expected behaviour: if gradle fails for any reason the Setup.hs build script should abort.

**Comment by mboes** [comment] 2016-11-25 10:30
@robinbb could you provide instructions to reproduce? Here's what I tried, which works as intended:

```
# Introduce a syntax error in a src/main/java/**/*.java file.
$ stack build sparkle
stack build sparkle
sparkle-0.3: build
Preprocessing library sparkle-0.3...
In-place registering sparkle-0.3...
Preprocessing executable 'sparkle' for sparkle-0.3...
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/mboes/src/tweag/sparkle/src/main/java/Helper.java:1: error: ';' expected
import java.util.Arrays();
                       ^
1 error
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.851 secs
setup: Command gradle build exited with failure code 1

--  While building package sparkle-0.3 using:
      /home/mboes/src/tweag/sparkle/.stack-work/dist/x86_64-linux-nix/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.22.5.0 build lib:sparkle exe:sparkle --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by mboes** [comment] 2016-11-25 10:31
Reassign until we have a repro.

**Comment by robinbb** [comment] 2016-11-25 21:36
I can't reproduce. If it happens again, I will open another issue. Closing.

**Closed by robinbb** 2016-11-25 21:36 UTC
